language: c
compiler: gcc

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev
      - libcmocka-dev

before_install:
  - pip install --user cpp-coveralls

script:
  - make test
  - make test2

after_success:
  - coveralls --gcov-options '\-lp'
