language: c
compiler: gcc

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev

before_install:
  - pip install --user cpp-coveralls

script:
  - make
  - ./example1
  - ./example2
  - ./cmptest

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
